### ISSUE TITLE
[HELP] Bytes

### ISSUE THREAD

**Issue by renanogueira** [genSouza/VP200-Server#1]
Olá, tudo bem com você?
Você poderia me ajudar com as notações que você tem no VP200Commands?
Eu gostaria de criar alguns a mais, por exemplo alinhar na linha que está e não na posição da tela..
Como eu posso fazer isso?
Seu comentário no código sobre ter encontrado no manual, não consegui achar nada sobre isso.. 👎 
Valeu!! 🥇 

ps: Um ótimo exemplo que você possui!

**Comment by genSouza** [comment]
Olá, tudo bem! Sobre as tags você pode utilizar este link:
http://kb.newland-id.com/index.php?n=NQuire.EscapeCommandCodes

Ele contém a lista de esc/pos compatíveis com o vp200. Você pode tentar uma das funções de alinhamento. Infelizmente não possuo mais acesso ao vp200 para realizar testes. Espero ter ajudado.
